# this way we generate the controller for "projects" resource
# it also generates the helpers and the assets
# note that we use the pluralized form for the "project" model,
# "projects_controller will deal with multiple project(s)""

# this also generates "spec/controllers/projects_controller_spec.rb"
$ bin/rails generate controller projects

# generating project model (the default type is string, so we don't have to specify them)
$ bin/rails generate model project name description
# but if we wanted to specify them explicitally, you can run this:
$ bin/rails generate model prohect name:string description:string

# run the migrations:
$ bin/rake db:migrate
# undo a migration:
$ bin/rake db:rollback


$ bin/rails generate controller tickets
$ bin/rails generate model ticket title:string description:text project:references

# to view the model generated by this command, see the file "db/schema.rb"
$ bin/rake db:migrate
# the test database
$ bin/rake db:test:prepare
# with large migrations, it's best to use the following command
$ bin/rake db:schema:load

$ bin/rails generate model user name:string email:string password_digest:string
$ bin/rake db:migrate db:test:prepare
